spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://8.142.125.160:3306/YDBlog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: xinke308!
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      min-evictable-idle-time-millis: 60000
      max-wait: 60000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j2
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

server:
  tomcat:
    max-http-form-post-size: 10MB
  port: 8096


#oss配置
oss:
  bucket:
    name: kumadoggy
  key:
    id: FY4ZgRBpnSxdChh9u8soGGNIFhxbPjUz2BxZTpUY
    secret: TqFaMhzCV_MBbhUAyaCDIXaRtUdfehRkefIsZ86K

#素材访问地址
img:
  url: 'https://zip.gewudi.com/'

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ry.time.admin.model.entity

location:
  upload: upload/